// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/encap/baseButton.vue')['default']
    BaseModal: typeof import('./src/components/baseModal.vue')['default']
    CreateModal: typeof import('./src/components/encap/createModal.vue')['default']
    CustomImage: typeof import('./src/components/CustomImage.vue')['default']
    IntelInpt: typeof import('./src/components/intelInput/intelInpt.vue')['default']
    Login: typeof import('./src/components/login/index.vue')['default']
    LoginForm: typeof import('./src/components/login/loginForm.vue')['default']
    RegisterForm: typeof import('./src/components/login/registerForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollSlider: typeof import('./src/components/scroll-slider.vue')['default']
  }
}

export {}
